In [2]:
import numpy as np
import pandas as pd

In [6]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

arr = np.array([0,1,2,3,4,5])
arr.dtype

dtype('int64')

In [7]:
# 2. Given a NumPy array 'arr', check if its data type is float64. arr = np.array([1.5, 2.6, 3.7])

arr = np.array([1.5, 2.6, 3.7])
print("yes" if arr.dtype == "float64" else "no")

yes


In [10]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([2+5j,8-6j,4+3j])
arr,arr.dtype

(array([2.+5.j, 8.-6.j, 4.+3.j]), dtype('complex128'))

In [15]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

arr = np.array([0,1,2,3,4,5])
arr = arr.astype('float32')
arr.dtype

dtype('float32')

In [16]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1.5, 2.6, 3.7])
arr = arr.astype("float32")
arr.dtype

dtype('float32')

In [20]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype.

def array_attributes(arr):
    return (arr.shape,arr.size,arr.dtype)

arr = np.linspace(2,9,12)
arr = arr.reshape(3,4)
shape, size, data_type = array_attributes(arr)
print(f"The shape of the array is : {shape}, size of the array is : {size}, data type of the array is : {data_type}")

The shape of the array is : (3, 4), size of the array is : 12, data type of the array is : float64


In [21]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

def array_dimension(arr):
    return arr.ndim

arr = np.linspace(2,9,12)
arr = arr.reshape(2,2,3)
print("The dimension of this numpy array is :", array_dimension(arr)) 

The dimension of this numpy array is : 3


In [35]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

def item_size_info(arr):
    return arr.size, arr.tobytes()

arr = np.linspace(2,9,12)
arr = arr.reshape(3,4)
size, bytecode = item_size_info(arr)
print(f"The size of the array is : {size}")
print(f"bytecode of total array is : {bytecode}")

The size of the array is : 12
bytecode of total array is : b'\x00\x00\x00\x00\x00\x00\x00@\x17]t\xd1E\x17\x05@.\xba\xe8\xa2\x8b.\n@F\x17]t\xd1E\x0f@.\xba\xe8\xa2\x8b.\x12@\xba\xe8\xa2\x8b.\xba\x14@F\x17]t\xd1E\x17@\xd1E\x17]t\xd1\x19@]t\xd1E\x17]\x1c@\xe9\xa2\x8b.\xba\xe8\x1e@\xba\xe8\xa2\x8b.\xba @\x00\x00\x00\x00\x00\x00"@'


In [39]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(arr):
    return arr.strides

arr = np.linspace(2,9,12)
arr = arr.reshape(2,2,3)
print("The strides of this array is :",array_strides(arr))

The strides of this array is : (48, 24, 8)


In [3]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

def shape_stride_relationship(arr):
    return arr.shape,arr.strides

arr = np.linspace(2,9,12)
arr = arr.reshape(2,2,3)
size, strides = shape_stride_relationship(arr)
print("The size of this array is :",size)
print("The strides of this array is :",strides)

The size of this array is : (2, 2, 3)
The strides of this array is : (48, 24, 8)


In [7]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

def create_zeros_array(n):
    return np.zeros(n)

create_zeros_array(5)

array([0., 0., 0., 0., 0.])

In [8]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
# NumPy array filled with ones of size `rows x cols`.

def create_zeros_array(rows,cols):
    return np.ones((rows,cols))

create_zeros_array(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)
    
generate_range_array(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

def generate_linear_space(start,stop,num):
    return np.linspace(start,stop,num)

generate_linear_space(1,20,12)

array([ 1.        ,  2.72727273,  4.45454545,  6.18181818,  7.90909091,
        9.63636364, 11.36363636, 13.09090909, 14.81818182, 16.54545455,
       18.27272727, 20.        ])

In [14]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
# identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
    return np.eye(n)

create_identity_matrix(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.

def to_array(lis):
    return np.array(lis)

to_array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [28]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

arr1 = np.array([2, 3, 4, 5, 7])
arr2 = arr1.view()
arr2[2] = 1
arr1[4] = 6
arr2,arr1

(array([2, 3, 1, 5, 6]), array([2, 3, 1, 5, 6]))

In [15]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def array_concatenation(arr1,arr2,axs):
    if axs==0: return np.concatenate((arr1,arr2),axis = 0)
    elif axs==1: return np.concatenate((arr1,arr2.T),axis = 1)
    else: return "invalid"

arr1 = np.array([[4, 7],[1, 6]])
arr2 = np.array([[2,3]])
specified_axis = int(input("enter the axis 0 or 1 : "))
print(f"The concatenation on axis {specified_axis} is :\n",array_concatenation(arr1,arr2,specified_axis))

enter the axis 0 or 1 :  1


The concatenation on axis 1 is :
 [[4 7 2]
 [1 6 3]]


In [ ]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy concatenate`.

def horizontal_concatenation(arr1,arr2):
    return np.concatenate((arr1,arr2.T),axis = 1)

arr1 = np.array([[4, 7],[1, 6]])
arr2 = np.array([[2,3]])
print("horizontal concatenation :",array_concatenation(arr1,arr2))

In [6]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

def vertically_stacks(*lis):
    if len(lis)==0: return "invalid"
    if len(lis)==1:return np.array(lis[0]) 
    arr = np.concatenate((np.array(lis[0]),np.array(lis[1])),axis = 0)
    for i in range(2,len(lis)):
        arr = np.concatenate((arr,np.array(lis[i])),axis = 0)
    return arr

vertically_stacks([[2,3]],[[4,5]],[[7,8]])

array([[2, 3],
       [4, 5],
       [7, 8]])

In [9]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

def range_array(start,stop,step):
    return np.arange(start,stop+1,step)

range_array(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

def equally_spaced_values():
    return np.linspace(0,1,10)

equally_spaced_values()

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

def logarithmically_spaced_values():
    return np.logspace(0,3,5)

logarithmically_spaced_values()

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [8]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 
# and 100.

arr = np.random.randint(1,100,size = (5,3))
df = pd.DataFrame(arr,columns = ['key1','key2','key3'])
df

key1  key2  key3
0    35    87    92
1    85    99    25
2    81     6    41
3     3    43    72
4    24    41    38

In [14]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
# with zeros. Use NumPy operations within the Pandas DataFrame.

def replaces(cx):
    cx.data[cx.data<0] = 0
    
df = pd.DataFrame({ "data" : np.random.randint(-10,11,size = 20)})
replaces(df)
print("mean : ",np.mean(df.data))
print("median : ",np.median(df.data))
print("variance : ",np.var(df.data))
print("standard deviation : ",np.std(df.data))
print("first quartile : ",np.percentile(df.data,[25]))
print("third quartile : ",np.percentile(df.data,[75]))

mean :  2.05
median :  0.0
variance :  6.9475
standard deviation :  2.6358110706194404
first quartile :  [0.]
third quartile :  [4.25]


In [10]:
# 26. Access the 3rd element from the given NumPy array. arr = np.array([10, 20, 30, 40, 50])

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


In [12]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array. arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr_2d[1][2]

6

In [13]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array. arr = np.array([3, 8, 2, 10, 5, 7])

arr = np.array([3, 8, 2, 10, 5, 7])
np.extract(arr>5,arr)

array([ 8, 10,  7])

In [14]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array. 
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

In [20]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array. 
#arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [17]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array

def extract_elements(arr, indices):
    row_indices, col_indices = indices[:, 0], indices[:, 1]
    extracted_elements = arr[row_indices, col_indices]
    return extracted_elements


arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
indices = np.array([[0, 2],
                    [1, 0],
                    [2, 1]])
extracted = extract_elements(arr, indices)
print(extracted)

[3 4 8]


In [6]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def greater_threshold(arr,threshold):
    return np.extract(arr>threshold,arr)

arr = np.array(list(map(int,input("enter the array elements: ").strip().split())))
threshold = int(input("enter the threshold value : "))
greater_threshold(arr,threshold)

enter the array elements:  0 1 2 3 4 5 6 7 8 9
enter the threshold value :  4


array([5, 6, 7, 8, 9])

In [23]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each
# dimension.

def arr3d_extract(arr3d,*index_arr):
    return arr3d[index_arr[0],index_arr[1],index_arr[2]]

arr3d = np.random.randint(1,9,size = (3,4,5))
first = [2,0,1]
second = [3,1,0]
third = [4,2,3]
arr3d_extract(arr3d,first,second,third)

array([4, 7, 4])

In [10]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

def two_conditions(arr):
    return arr[(arr>5) & (arr<15)]

arr = np.random.randint(1,20,size = (10,))
two_conditions(arr)

array([10, 12, 13,  7,  9, 13,  8])

In [25]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

def arr2d_extract(arr2d,*index_arr):
    return arr2d[index_arr[:][0],index_arr[:][1]]

arr2d = np.random.randint(1,9,size = (4,5))
first = [1,3]
second = [0,4]
third = [2,1]
arr2d_extract(arr2d,first,second,third)

array([5, 6])

In [16]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.random.randint(1,20,size = (3,3))
print("before broadcast :\n",arr)
arr = arr + 5
print("after broadcast :\n",arr)

before broadcast :
 [[12 19  3]
 [ 5 15  9]
 [12  1 10]]
after broadcast :
 [[17 24  8]
 [10 20 14]
 [17  6 15]]


In [29]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
# corresponding element in arr1 using NumPy broadcasting.

arr1 = np.random.randint(1,10,size = (1,3))
arr2 = np.random.randint(1,10,size = (3,4))
print("arr1 :\n",arr1)
print("arr2 :\n",arr2)
print("arr1 * arr2 :\n",arr1.T * arr2)

arr1 :
 [[9 3 7]]
arr2 :
 [[2 5 8 1]
 [2 4 3 9]
 [5 8 4 7]]
arr1 * arr2 :
 [[18 45 72  9]
 [ 6 12  9 27]
 [35 56 28 49]]


In [36]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

arr1 = np.random.randint(1,10,size = (1,4))
arr2 = np.random.randint(1,10,size = (4,3))
print("arr1 :\n",arr1)
print("arr2 :\n",arr2)
print("arr1 + arr2 :\n",arr1.T + arr2)

arr1 :
 [[1 7 7 5]]
arr2 :
 [[4 3 5]
 [2 9 2]
 [6 3 9]
 [7 9 4]]
arr1 + arr2 :
 [[ 5  4  6]
 [ 9 16  9]
 [13 10 16]
 [12 14  9]]


In [37]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1 = np.random.randint(1,10,size = (3,1))
arr2 = np.random.randint(1,10,size = (1,3))
print("arr1 :\n",arr1)
print("arr2 :\n",arr2)
print("arr1 + arr2 :\n",arr1 + arr2)

arr1 :
 [[6]
 [9]
 [6]]
arr2 :
 [[2 5 7]]
arr1 + arr2 :
 [[ 8 11 13]
 [11 14 16]
 [ 8 11 13]]


In [44]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

arr1 = np.random.randint(1,10,size = (2,3))
arr1 = arr1[:,:2]
arr2 = np.random.randint(1,10,size = (2,2))
print("arr1 :\n",arr1)
print("arr2 :\n",arr2)
print("arr1 + arr2 :\n",arr1 * arr2)

arr1 :
 [[6 7]
 [1 6]]
arr2 :
 [[2 3]
 [1 8]]
arr1 + arr2 :
 [[12 21]
 [ 1 48]]


In [46]:
# 41. Calculate column wise mean for the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.mean(axis = 0))

[2.5 3.5 4.5]


In [3]:
# 42. Find maximum value in each row of the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.max(axis = 1))

[3 6]


In [53]:
# 43. For the given array, find indices of maximum value in each column. arr = np.array([[1, 2, 3], [4, 5, 6]])

arr = np.array([[1, 2, 3], [4, 5, 6]])
lis = list(arr.max(axis = 0))
for i in lis:
    for j in range(len(arr)):
        for k in range(len(arr[0])):
            if arr[j][k]==i: print(f"The index of {i} is : ({j},{k})")

The index of 4 is : (1,0)
The index of 5 is : (1,1)
The index of 6 is : (1,2)


In [4]:
# 44. For the given array, apply custom function to calculate moving sum along rows. arr = np.array([[1, 2, 3], [4, 5, 6]])

from functools import reduce

def moving_sum(arr):
    l=[]
    for i in arr:
        l.append(reduce(lambda x,y : x+y, i))
    return l

arr = np.array([[1, 2, 3], [4, 5, 6]])
moving_sum(arr)

[6, 15]

In [7]:
# 45. In the given array, check if all elements in each column are even. arr = np.array([[2, 4, 6], [3, 5, 7]])

arr = np.array([[2, 4, 6], [3, 5, 7]])
print((arr[0]&1==0) & (arr[1]&1==0))

[False False False]


In [10]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix. 
# original_array = np.array([1, 2, 3, 4, 5, 6])

def reshaped(arr,m,n):
    return arr.reshape(m,n)

original_array = np.array([1, 2, 3, 4, 5, 6])
m = int(input("enter number of rows : "))
n = int(input("enter number of columns : "))
reshaped(arr,m,n)

enter number of rows :  3
enter number of columns :  2


array([[2, 4],
       [6, 3],
       [5, 7]])

In [12]:
# 47. Create a function that takes a matrix as input and returns the flattened array. input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flattened_array(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array(input_matrix)

array([1, 2, 3, 4, 5, 6])

In [4]:
# 48. Write a function that concatenates two given arrays along a specified axis. array1 = np.array([[1, 2], [3, 4]]) 
# array2 = np.array([[5, 6], [7, 8]])

def array_concatenation(arr1,arr2,axs):
    if axs==0: return np.concatenate((arr1,arr2),axis = 0)
    elif axs==1: return np.concatenate((arr1,arr2),axis = 1)
    else: return "invalid"

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
specified_axis = int(input("enter the axis 0 or 1 : "))
print(f"The concatenation on axis {specified_axis} is :\n",array_concatenation(array1,array2,specified_axis))

enter the axis 0 or 1 :  1


The concatenation on axis 1 is :
 [[1 2 5 6]
 [3 4 7 8]]


In [11]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
# original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_subarrays(arr,n,axs):
    return np.split(arr,n,axis = axs)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
specified_axis = int(input("enter the axis 0 or 1 : "))
split_subarrays(original_array,3,specified_axis)

enter the axis 0 or 1 :  0


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [12]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices. original_array = np.array([1, 2, 3, 4, 5])
# indices_to_insert = [2, 4]
# values_to_insert = [10, 11]
# indices_to_delete = [1, 3]

def Insert_delete(arr,ip,iv,dp):
    arr = np.insert(arr,ip,iv)
    arr = np.delete(arr,dp)
    return arr

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
Insert_delete(original_array,indices_to_insert,values_to_insert,indices_to_delete)

array([ 1, 10,  4, 11,  5])

In [3]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
# Perform element-wise addition between `arr1` and `arr2`.

arr1 = np.random.randint(1,50,size = (10,))
arr2 = np.arange(1,11)
print(arr1+arr2)

[ 2 47 38 47 52 26 19 37 29 28]


In [4]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
# from 1 to 10. Subtract `arr2` from `arr1` element-wise.

arr1 = np.array(range(10,1,-1))
arr2 = np.arange(1,10)

print(arr1-arr2)

[ 9  7  5  3  1 -1 -3 -5 -7]


In [3]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
# Perform element-wise multiplication between `arr1` and `arr2`.
arr1 = np.random.randint(1,10,size = (5,))
arr2 = np.arange(1,6)
print(arr1*arr2)

[ 7  6 27 32 30]


In [4]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
# to 5. Perform element-wise division of `arr1` by `arr2`.

arr1 = np.arange(2,11,2)
arr2 = np.arange(1,6)
print(arr1/arr2)

[2. 2. 2. 2. 2.]


In [3]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

arr1 = np.arange(1,6)
arr2 = arr1.copy()[::-1]
print(np.power(arr1,arr2))

[ 1 16 27 16  5]


In [7]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings. 
# arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

find_substring = lambda x, y : len(x[x == y])

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
sp_substring = input("enter the specific substring : ")
find_substring(arr,sp_substring)

enter the specific substring :  hello


3

In [14]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
# arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

uppercase_substring = lambda x : x[x == np.char.upper(x)]

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_substring(arr)

array(['GPT'], dtype='<U6')

In [17]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string. 
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

replaces_occurrences = lambda arr,wc,bw : np.char.replace(arr,wc,bw)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
wc = input("enter the string you want change : ")
bw = input("enter the string, by that you want to change it : ")
replaces_occurrences(arr,wc,bw)

enter the string you want change :  grape
enter the string, by that you want to change it :  orange


array(['apple', 'banana', 'orange', 'pineapple'], dtype='<U9')

In [20]:
# 59. Write a function that concatenates strings in a NumPy array element-wise. arr1 = np.array(['Hello', 'World']) 
# arr2 = np.array(['Open', 'AI'])

concatenates_strings = lambda arr1, arr2 : np.char.add(arr1,arr2)

arr1 = np.array(['Hello', 'World']) 
arr2 = np.array(['Open', 'AI'])
concatenates_strings(arr1,arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [26]:
# 60. Write a function that finds the length of the longest string in a NumPy array. arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

length_of_the_longest_string = lambda arr : max(list(map(lambda x : len(x),arr)))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
length_of_the_longest_string(arr)

9

In [30]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
# standard deviation of the dataset using NumPy's functions.

dataset = np.random.randint(1,1000,size = 100)
print("Mean of this dataset is :",dataset.mean())
print("Median of this dataset is :",np.median(dataset))
print("Variance of this dataset is :",dataset.var())
print("Standard deviation of this dataset is :",dataset.std())

Mean of this dataset is : 483.73
Median of this dataset is : 439.0
Variance of this dataset is : 97341.33709999999
Standard deviation of this dataset is : 311.99573250286613


In [3]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset

df = pd.Series(np.random.randint(1,100,size = 50)).describe()
print("25th percentiles of this dataset is :",df["25%"])
print("75th percentiles of this dataset is :",df["75%"])

25th percentiles of this dataset is : 32.5
75th percentiles of this dataset is : 76.0


In [4]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's 
# `corrcoef` function.

arr1 = np.random.randint(1,100,size = 50)
arr2 = np.random.randint(1,100,size = 50)
np.corrcoef(arr1,arr2)

array([[ 1.        , -0.13845108],
       [-0.13845108,  1.        ]])

In [5]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

arr1 = np.random.randint(1,100,size = (2,3))
arr2 = np.random.randint(1,100,size = (3,4))
arr1.dot(arr2)

array([[16151,  7252, 10070, 13035],
       [12260,  5736,  8474, 11258]])

In [9]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
# percentiles along with the first and third quartiles.

dif_percentiles = np.percentile(np.random.randint(10,1000,size = 50), [10,50,90,25,75])
print("The 10th percentile of this data is :",dif_percentiles[0])
print("The 50th percentile of this data is :",dif_percentiles[1])
print("The 90th percentile of this data is :",dif_percentiles[2])
print("The first quartile of this data is :",dif_percentiles[3])
print("The third quartile of this data is :",dif_percentiles[4])

The 10th percentile of this data is : 129.9
The 50th percentile of this data is : 679.0
The 90th percentile of this data is : 937.7
The first quartile of this data is : 260.75
The third quartile of this data is : 842.75


In [3]:
# 66. Create a NumPy array of integers and find the index of a specific element.

def search_element(arr,se):
    if se not in arr:
        return "This element is not in this array"
    else:
        return np.where(arr == se)[0]
    
arr = np.random.randint(1,10,size = 10)
se = int(input("enter the element you want to search in this array"))
search_element(arr,se)

enter the element you want to search in this array 4


array([3])

In [10]:
# 67. Generate a random NumPy array and sort it in ascending order.

arr = np.random.randint(1,10,size = 10)
print("before sort :",arr)
arr = np.sort(arr)
print("after sort :",arr)

before sort : [7 7 3 7 8 1 3 7 2 6]
after sort : [1 2 3 3 6 7 7 7 7 8]


In [14]:
# 68. Filter elements >20  in the given NumPy array. arr = np.array([12, 25, 6, 42, 8, 30])

arr = np.array([12, 25, 6, 42, 8, 30])
list(filter(lambda x : x>20,arr))

[25, 42, 30]

In [17]:
# 69. Filter elements which are divisible by 3 from a given NumPy array. arr = np.array([1, 5, 8, 12, 15])

arr = np.array([1, 5, 8, 12, 15])
np.extract(arr%3==0,arr)

array([12, 15])

In [20]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array. arr = np.array([10, 20, 30, 40, 50])

arr = np.array([10, 20, 30, 40, 50])
np.extract((20<=arr) & (arr<=40),arr)

array([20, 30, 40])

In [31]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder. arr = np.array([1, 2, 3])

arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
if byte_order == '=':
    print("The array is in the system's native byte order.")
elif byte_order == '<':
    print("The array is in little-endian byte order.")
elif byte_order == '>':
    print("The array is in big-endian byte order.")
else:
    print("Unknown byte order.")

The array is in the system's native byte order.


In [28]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`. arr = np.array([1, 2, 3], dtype=np.int32)

arr = np.array([1, 2, 3], dtype=np.int32)
swapped = arr.view(np.uint8).reshape(-1, 4)[:, ::-1].reshape(-1).view(np.int32)
print(swapped)

[16777216 33554432 50331648]


In [29]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`. 
# arr = np.array([1, 2, 3], dtype=np.int32)

arr = np.array([1, 2, 3], dtype=np.int32)
swapped = arr.newbyteorder()
print("Original array:", arr)
print("Byte-swapped array:", swapped)

Original array: [1 2 3]
Byte-swapped array: [16777216 33554432 50331648]


In [30]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`. 
# arr = np.array([1, 2, 3], dtype=np.int32)

arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':
    swapped = arr.newbyteorder()
else:
    swapped = arr

print("Original array:", arr)
print("Conditionally byte-swapped array:", swapped)

Original array: [1 2 3]
Conditionally byte-swapped array: [16777216 33554432 50331648]


In [ ]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`. 
# arr = np.array([1, 2, 3], dtype=np.int32)

arr = np.array([1, 2, 3], dtype=np.int32)
byte_order = arr.dtype.byteorder
if byte_order == '=':  
    system_endian = 'little' if np.little_endian else 'big'
    print(f"The array is already in the system's native {system_endian}-endian byte order. No swapping necessary.")
elif byte_order == '<':  
    if not np.little_endian:
        print("The system is big-endian, so byte swapping is necessary.")
    else:
        print("The system is little-endian, and so is the array. No swapping necessary.")
elif byte_order == '>':  
    if np.little_endian:
        print("The system is little-endian, so byte swapping is necessary.")
    else:
        print("The system is big-endian, and so is the array. No swapping necessary.")

In [27]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

arr1 = np.arange(1,11)
copy_arr = arr1.copy()
print("before modification data is :\n",arr1)
print("before modification data_copy is :\n",copy_arr)
copy_arr[3] = 11
print("after modification data is :\n",arr1)
print("after modification data_copy is :\n",copy_arr)

before modification data is :
 [ 1  2  3  4  5  6  7  8  9 10]
before modification data_copy is :
 [ 1  2  3  4  5  6  7  8  9 10]
after modification data is :
 [ 1  2  3  4  5  6  7  8  9 10]
after modification data_copy is :
 [ 1  2  3 11  5  6  7  8  9 10]


In [25]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

matrix = np.matrix(np.random.randint(1,10,size = (3,3)))
view_slice = matrix[0:2,1:3]
print("before modification data is :\n",matrix)
print("before modification data_copy is :\n",view_slice)
view_slice[1,0] = 11
print("after modification data is :\n",matrix)
print("after modification data_copy is :\n",view_slice)

before broadcasting data is :
 [[5 4 5]
 [7 7 4]
 [6 5 7]]
before broadcasting data_copy is :
 [[4 5]
 [7 4]]
after broadcasting data is :
 [[ 5  4  5]
 [ 7 11  4]
 [ 6  5  7]]
after broadcasting data_copy is :
 [[ 4  5]
 [11  4]]


In [21]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

array_a = np.arange(1,13).reshape(4,3)
view_b = array_a[0:3,1:3] 
print("before broadcasting data is :\n",array_a)
print("before broadcasting data_copy is :\n",view_b)
view_b  = view_b + 5
print("after broadcasting data is :\n",array_a)
print("after broadcasting data_copy is :\n",view_b)

before broadcasting data is :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
before broadcasting data_copy is :
 [[2 3]
 [5 6]
 [8 9]]
after broadcasting data is :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
after broadcasting data_copy is :
 [[ 7  8]
 [10 11]
 [13 14]]


In [23]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from 
# orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

orig_array = np.random.randint(1,8,size = (2,4))
reshaped_view = orig_array.reshape(4,2)
print("before modification data is :\n",orig_array)
print("before modification data_copy is :\n",reshaped_view)
reshaped_view[1][0] = 24
print("after modification data is :\n",orig_array)
print("after modification data_copy is :\n",reshaped_view)

before modification data is :
 [[1 6 4 1]
 [4 2 7 5]]
before modification data_copy is :
 [[1 6]
 [4 1]
 [4 2]
 [7 5]]
after modification data is :
 [[ 1  6 24  1]
 [ 4  2  7  5]]
after modification data_copy is :
 [[ 1  6]
 [24  1]
 [ 4  2]
 [ 7  5]]


In [22]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

data = np.random.randint(1,10,size = (3,4))
data_copy = np.extract(data>5,data)
print("before modification data is :\n",data)
print("before modification data_copy is :",data_copy)
data_copy[1] = 24
print("after modification data is :\n",data)
print("after modification data_copy is :",data_copy)

before modification data is :
 [[2 4 8 3]
 [1 1 1 7]
 [8 9 6 5]]
before modification data_copy is : [8 7 8 9 6]
after modification data is :
 [[2 4 8 3]
 [1 1 1 7]
 [8 9 6 5]]
after modification data_copy is : [ 8 24  8  9  6]


In [31]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

A = np.matrix(np.random.randint(1,10,size = (3,4)))
B = np.matrix(np.random.randint(1,10,size = (3,4)))
print("addition operation :\n",A+B)
print("substaction operation :\n",A-B)

addition operation :
 [[ 3  7 14 13]
 [ 5  9 15  5]
 [13  7  8  7]]
substaction operation :
 [[ 1 -1 -2 -5]
 [-1 -1 -1  1]
 [-5  1 -4 -5]]


In [29]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

C = np.matrix(np.random.randint(1,10,size = (3,2)))
D = np.matrix(np.random.randint(1,10,size = (2,4)))
C@D

matrix([[ 28,  52,  51,  18],
        [ 35, 101,  93,  81],
        [  7,  17,  16,  11]])

In [28]:
# 83. Create a matrix `E` and find its transpose.

E = np.matrix(np.random.randint(1,10,size = (3,4)))
np.transpose(E)

matrix([[2, 3, 7],
        [4, 1, 5],
        [4, 9, 2],
        [5, 8, 6]])

In [26]:
# 84. Generate a square matrix `F` and compute its determinant.

F = np.matrix(np.random.randint(1,10,size = (4,4)))
np.linalg.det(F)

-254.99999999999991

In [25]:
# 85. Create a square matrix `G` and find its inverse.

G = np.matrix(np.random.randint(1,10,size = (4,4)))
np.linalg.inv(G)

matrix([[-0.26285714,  0.37714286, -0.2       ,  0.6       ],
        [-0.24571429, -0.12571429,  0.4       , -0.2       ],
        [ 0.23428571, -0.20571429,  0.2       , -0.6       ],
        [ 0.44571429, -0.07428571, -0.4       ,  0.2       ]])